- name: Mapping the object configuration of remote hosts
  tags:
    - setup_object_configurations


  block:
    - name: Create parent directories
      ansible.builtin.file:
        path: /etc/icinga2/zones.d/master/
        state: directory
        mode: '0755'
        owner: odennav
        group: odennav
      tags:
        - create_master_zone_dir 


    - name: Touch the conf file for remote server
      ansible.builtin.file:
        path: /etc/icinga2/zones.d/master/{{ inventory_hostname }}.conf
        state: touch
        mode: '0755'
      tags:
        - touch_hostname_conf


    - name: generate object config file from template
      template:
        src: /icinga-monitoring-alerting-systems/templates/{{ inventory_hostname }}.j2
        dest: /etc/icinga2/zones.d/master/{{ inventory_hostname }}.conf
        owner: odennav
        group: odennav
        mode: 0644
      notify: restart_icinga2

    handlers:
    - name: restart_icinga2
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: icinga2.service


          
